name: Terraform CI

on:
  push:
    branches:
      - main
      - feature/subnet

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # 4. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 5. Terraform Init
      - name: Terraform Init
        working-directory: ./parent_module
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        working-directory: ./parent_module
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        working-directory: ./parent_module
        run: terraform plan
